[package]
name = "ziyy"
version = "2.0.3"
readme = "README.md"
repository = "https://github.com/ziyy-dev/ziyy-rs.git"
edition = "2024"
description = "Terminal Styling using HTML-like syntax."
license = "MIT OR Apache-2.0"
keywords = ["terminal", "ansi", "style", "html", "cli"]
categories = ["command-line-interface", "command-line-utilities"]

[workspace]
members = ["ziyy-core", "ziyy-proc"]

[dependencies]
terminal_size = "0.4.2"
ziyy-core = { path = "ziyy-core", version = "0.1.2", features = [
    "unstable",
    "parallel",
] }
