[package]
edition = "2021"
name    = "ziyy-core"
version = "0.1.0"

[lib]
name = "ziyy_core"
path = "src/lib.rs"

[features]
bindings = []
default  = ["bindings"]
uncommon = []

[dependencies]
ego-tree = "0.10.0"
smallvec = "1.15.1"
terminfo = { version = "0.9.0", optional = true }
